### ISSUE TITLE
Signed In Successfully does not go away

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#117]
As an existing user, go to ticket requests page
http://localhost:8080/tickets/request/2--fall-campout-xxii
Sign in

Signed In Successfully flash never goes away until you navigate away
![Screenshot 2024-05-05 at 11 20 03 AM](https://github.com/fnf-org/TicketBooth/assets/1203197/f1cd0e0a-66ef-457f-aed0-6ea474195844)

**Comment by beingmattlevy** [comment]
![Screenshot 2024-05-05 at 11 26 11 AM](https://github.com/fnf-org/TicketBooth/assets/1203197/000519e2-4654-47ba-95f5-7b0ce726b682)

**Comment by yarunluon** [comment]
As of a4e07272bef77c234aa318f6e79c83969e71a0d5, all banners disappear as expected now.
