### ISSUE TITLE
Registration will take you to ticket request for next event

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#121]
As a user without an account, I register
http://localhost:8080/users/sign_up

Registration works. I get taken to the next upcoming event:
http://localhost:8080/events/4--next-event/ticket_requests/new

No option to signup for the summer campout.
http://localhost:8080/events/1--summer-campout/ticket_requests/new

This is workable as long as we don't have 2 ticketings going on at once.

**Comment by yarunluon** [comment]
@beingmattlevy , some questions about your description. 

1. The event `4--next-event` was the next event and the event `1--summer-campout` was after `4--next-event`?
2. Users are not able to request tickets for `1--summer-campout`?
3. Did the ticket window for `1--summer-campout` overlap with `4--next-event` or the current date of registration?

**Comment by kigster** [comment]
I believe this works correctly as designed.

The `home#index` action chooses which ticket request to route you based on the start date of the event: the first event to start is automatically redirected.

The app WAS NEVER DESIGNED TO SUPPORT MULTIPLE event ticket requests at the same time.

Please close this or make it a feature request.

**Comment by kigster** [comment]
Closing for now
