### ISSUE TITLE
Users are able to request tickets with no maximum after making request

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#131]
After making a request and waiting for approval, users can go back into the ticket request and edit the number of tickets requested. There is no maximum bound on the number of possible tickets to request.

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/21b79eb4-a5bd-4a15-bede-a4db1daa06d0)

https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3020
user: `tickets+requested01@fnf.org`
pass: `ethical-STRIATED-dormer`

**Comment by kigster** [comment]
I believe it's been fixed, but worth verifying.

**Comment by beingmattlevy** [comment]
Behavior still there. Can confirm. 
I was able to set adults to 10 before it was even approved.

**Comment by yarunluon** [comment]
I'm still experiencing a version of this bug. Use this URL: ([ticket_request/3027](https://tickets.fnf.events/events/14/ticket_requests/3027)) to test the behavior. I deleted ticket_request #3020 testing [which user roles can delete tickets](https://github.com/fnf-org/TicketBooth/issues/149).

**Comment by yarunluon** [comment]
As of fd9e2acc9b165c2e18d4997647a249b992cebedc, users cannot request more than the max allowed.  However, it should be noted that all guest names need to be entered for the request to be saved.
