### ISSUE TITLE
"Home" button in nav bar is broken

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#133]
Clicking on the "Home" button in the navbar generates a POST 404 message in the console.
```
POST https://tickets.fnf.events/ 404 (Not Found)
```

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/4a88caba-f79b-4da4-b4ff-01bcde3e6200)
![home-button-broken](https://github.com/fnf-org/TicketBooth/assets/1328337/cec3c854-3d37-4842-9a39-11cd5beafe1f)

User: [tickets+requested@fnf.org](mailto:tickets+requested@fnf.org)
Pass: `ethical-STRIATED-dormer`

Expected behavior is for the user to be taken to a "Home" page or maybe some page that looks like a dashboard.

**Comment by yarunluon** [comment]
Partially complete. 

# Works for admin accounts
For admin accounts "Home" button was removed, and Gearhead goes to main event page.
![gearhead-goes-home](https://github.com/fnf-org/TicketBooth/assets/1328337/9fc2c24c-7415-4f60-bf72-ea59b5da59d7)

# Doesn't work for user accounts
The same behavior is still happening for user accounts. Suggest hiding the "Home" button like for Admin accounts. The Button is in a `<form>` component that is trying to `POST`

![user-home-button](https://github.com/fnf-org/TicketBooth/assets/1328337/b8857802-f6e3-4f72-ab5a-219f5e901f41)

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/2be2a9b8-0205-4b2f-8b32-680e140f1273)

**Comment by kigster** [comment]
This has been fixed. There is no longer a Home button. Just the logo.
