### ISSUE TITLE
Kids names are asked to be entered multiple times on the same form

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#134]
Kids names are asked to be listed multiple times in the same form.

Expected behavior is to list the children's names once. Preferably in the Guest input fields and not in the textfield.

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/f9910807-509b-4922-85e4-8254e724b0af)

URL: https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3021/edit
User: [tickets+kids@fnf.org](mailto:tickets+kids@fnf.org)
Pass: `postman-ozone-BETEL`

**Comment by yarunluon** [comment]
Although additional features were added around Kids, as of 5c234bb1679554f8e0b53ef1f0571d092209466f, users are still asked to enter kid's names twice

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/394b7ade-df94-45c1-850c-766ceb34e1e4)

**Comment by beingmattlevy** [comment]
Removed the duplicate language above the open text field.

**Comment by beingmattlevy** [comment]
Will go away when PR is mereged

**Comment by yarunluon** [comment]
As of fd9e2acc9b165c2e18d4997647a249b992cebedc, the copy about entering kids names has been removed

![image](https://github.com/fnf-org/TicketBooth/assets/1328337/95b769a2-d682-4aa5-881a-8b1b383c9988)
