### ISSUE TITLE
Unable to edit ticket request

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#141]
Users and admins are unable to update ticket requests. A server notification is sent requesting that all names be filled out. This notification is sometimes shown. 

Url: https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3024/edit

**Requiring guest names to be filled out should not be required when updating a ticket request:**
1. Users may not know their guests until late in the ticketing process
2. Admins need to leave notes and make adjustments to the ticket requests not related to guest names

**Reproduce**
1. Go to https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3024/edit
4. Log-in with account details in this issue
5. Modify the number of tickets requested
6. Save the results

**New Relic logs:** 
[Error] https://onenr.io/07jbAepN3Ry
[Notification] https://onenr.io/0BQreoqmEjZ

```json
{
  "entity.guid": "MzQ4MjEzMnxBUE18QVBQTElDQVRJT058MTAzNTg2MjYxMw",
  "entity.guids": "MzQ4MjEzMnxBUE18QVBQTElDQVRJT058MTAzNTg2MjYxMw",
  "entity.name": "TicketBooth on EC2",
  "hostname": "app.re1.re",
  "level": "ERROR",
  "message": "  \nActionView::Template::Error (undefined method `name' for nil:NilClass):\n    16: \n    17:       - if signed_in?\n    18:         Signed in as\n    19:         = \"#{@user.name} <#{@user.email}>\"\n    20:       - else\n    21:         = turbo_frame_tag :turbo_login do\n    22:           = render partial: \"devise/shared/login\", layout: false, locals: { resource: devise_mapping.singular, resource_name: devise_mapping.name, redirect_to: new_event_ticket_request_url(@event) }\n  \napp/views/ticket_requests/_form.html.haml:19\napp/views/ticket_requests/edit.html.haml:4\napp/controllers/ticket_requests_controller.rb:181:in `update'\n",
  "newrelic.logPattern": "nr.DID_NOT_MATCH",
  "newrelic.source": "logs.APM",
  "span.id": "e145835d3ec01e1a",
  "timestamp": 1715354710373,
  "trace.id": "5f490d41592dce51593b6a81a75aba17"
}
```
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/5ec4b82c-af61-4db0-a228-c388647af5e3)

![cannot-update-ticket-request](https://github.com/fnf-org/TicketBooth/assets/1328337/bd6b9e75-d2ea-462c-be9f-17057c994a97)

User: [tickets+requested02@fnf.org](mailto:tickets+requested@fnf.org)
Pass: `ethical-STRIATED-mouse`

**Comment by beingmattlevy** [comment]
This is related to the max ticket request issue.

**Comment by beingmattlevy** [comment]
Will retest once payments merge is in.

**Comment by kigster** [comment]
@yarunluon is there any validation we want to do on the guests? Is it valid for the ticket request to not have any guests filled out?

**Comment by yarunluon** [comment]
I prefer to keep the existing minimal validation that existed in the app >`v1.0.1` which was to ensure all guest names were filled out before entering the payment flow.

**Comment by yarunluon** [comment]
I also think this specific Issue can be Closed. I've confirmed Guests and Admins can update ticket requests. For new unexpected behavior, I'm comfortable creating new Issues to track. 

![update-ticket-request-success](https://github.com/fnf-org/TicketBooth/assets/1328337/a5c25d55-53a1-4048-8782-7f1fb1e24cd1)
