### ISSUE TITLE
Re-enable EALD links in ticket approval email

### ISSUE THREAD

**Issue by beingmattlevy** [fnf-org/TicketBooth#148]
EALD links in ticket request approval email template were commented out due to broken links
Once we enable EALD payments, we can enable this link again.

**Comment by yarunluon** [comment]
Linking the related ticket. 
https://github.com/fnf-org/TicketBooth/issues/130

**Comment by yarunluon** [comment]
EA/LD link is hidden as of fd9e2acc9b165c2e18d4997647a249b992cebedc
