### ISSUE TITLE
Ticket requesters cannot delete their own ticket requests

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#149]
**Describe the bug**
Ticket requesters cannot delete their own ticket requests. However, Admins can delete ticket requests. As a workaround, users can ask Admins to delete their ticket requests.

**To Reproduce**
1. Go to https://tickets.fnf.events/events/14/ticket_requests/3027. Log in as necessary. See login credentials below. 
2. Click on "Delete this Ticket Request"
3. Refresh page
5. Ticket request still loads. 

**Note**
Admins can delete ticket requests. Users cannot delete their own ticket requests.

**Expected behavior**
Users should be able to delete their own ticket requests. 

**Screenshots**
![cannot-delete-request](https://github.com/fnf-org/TicketBooth/assets/1328337/c40dd3b3-faf9-41e4-9ea8-20514a4df7af)

**Version info**  
App Version: `1.0.1`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`  

**Credentials**
[https://tickets.fnf.events/events/14/ticket_requests/3027](https://tickets.fnf.events/events/14/ticket_requests/3027)
tickets+requested01@fnf.org
`ethical-STRIATED-dormer`

**Comment by beingmattlevy** [comment]
Issue is a calling delete when destroy is needed. 
Will fix when updates routes are merged in from big payments merge

Issue is in views/ticket_request/show.html.haml
          = button_to "Delete this Ticket Request ✘ ", event_ticket_request_path(@event, @ticket_request), class: 'btn btn-warning', method: :delete, data: { "turbo-confirm": "Are you sure?" }

Should be destroy. But path is wrong here so need to wait till other changes are in

**Comment by kigster** [comment]
I disagree — I think we should allow deleting your own ticket request until it's been either paid for, or approved. It should be possible to go back and change your mind, unless someone approved it.

**Comment by kigster** [comment]
> Issue is a calling delete when destroy is needed. Will fix when updates routes are merged in from big payments merge
> 
> Issue is in views/ticket_request/show.html.haml = button_to "Delete this Ticket Request ✘ ", event_ticket_request_path(@event, @ticket_request), class: 'btn btn-warning', method: :delete, data: { "turbo-confirm": "Are you sure?" }
> 
> Should be destroy. But path is wrong here so need to wait till other changes are in

I don't think this is correct. 

Method delete invokes the destroy action. I tested and it works.

I think @yarunluon ia saying users should not BE ABLE TO delete their own ticket requests. 

I am saying they should unless the ticket is other approved or paid for.

**Comment by beingmattlevy** [comment]
I disabled the button for now
GIt commit 0a6198390ee4f1e155c56d5daec4d112a9c11a12

**Comment by yarunluon** [comment]
I'm fine closing this ticket for now. For future reference, my preference is for both Ticket Requesters and Admins to be able to delete tickets.

**Comment by kigster** [comment]
Why would the admins need to be able to delete ticket requests?

They already can approve or decline it.

The reason only the ticket request submitted should be able to delete the ticket request is if it hasn't been paid for yet, and perhaps it was created in error.

Please realize that deleting ticket request is an irreversible operation and it physically deletes the request from the database, leaving no record of the ticket request being there in the first place.

Admins should never be able to delete other people's requests. They can decline it and it will remain as a record.

**Comment by kigster** [comment]
I created a ticket request as a test and now I cannot delete it. This is a bad user experience.

I should be able to delete it if i haven't paid for it.

**Comment by yarunluon** [comment]
The old version of TicketBooth did not have a delete button so an addition of a button in any form is a bonus for me. Not having a delete button is the status quo and I'm also fine with that. 

> Why would the admins need to be able to delete ticket requests?

Admins get requests from ticket requesters to "delete" their tickets. For house keeping reasons, Admins want to clear tickets to understand the current state of tickets.

> Please realize that deleting ticket request is an irreversible operation and it physically deletes the request from the database, leaving no record of the ticket request being there in the first place.

We're probably working with different levels of the term "delete". I'm only speaking at a UI level and you're referencing a DB level. "Hiding" and "Deleting" a ticket request are the same to me. How this is represented in the DB doesn't matter to me.

**Comment by kigster** [comment]
@yarunluon the delete will be working for this release as follows:

- The delete button will only show on unpaid ticket requests
- The delete button will only be shown to ticket request owner or event or site admin
- The same as above would be able to delete the ticket request.
- Instead of physically deleting the request from the database without a trace, we'll use "logical delete" by marking it deleted but keeping a record in the database. 
- This will allow the ticket user to submit another request.

For each event, and each user there could be any number of logically deleted ticket requests and only one "live" ticket request.

**Comment by yarunluon** [comment]
This makes sense to me. Would it be easier to phrase it as "Cancel the ticket request" as the "logical delete" at the UI level? We can reserve "Delete" for when we actually remove records from the DB like you said.

**Comment by yarunluon** [comment]
Oh, I see we are already saying "Cancel" in the UI. Logical delete works for me.
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/55293867-e4d5-4922-ad26-ec7a409e6237)
