### ISSUE TITLE
"Update" button should be disabled until there is input in the "Current Password" field

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#153]
**Describe the bug**
The "Update" button should be disabled until there is a value in the "Current password" field. Otherwise the user may click "Update" without entering the current password and they will get a rejection message from the server. This behavior will confuse the user if they did not see the "Current password" button.

**To Reproduce**
1. Log in
2. Go to https://tickets.fnf.events/users/edit?
3. Change the First or Last name field
4. Click on "Update password"

**Expected behavior**
The "Update" button should be disabled until there is a value in the "Current password" field

**Screenshots**
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/5ad79d10-fabd-466b-935b-4c5443da40ae)

**Credentials**

URL: [https://tickets.fnf.events/users/edit?](https://tickets.fnf.events/users/edit?)  
User: `tickets+requested01@fnf.org`  
Pass: `ethical-STRIATED-dormer`  

**Version info**  
App Version: `1.0.1`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`

**Comment by kigster** [comment]
This is not really a bug. The server already produces a valid error message when the current password is not provided. Disabling the button duplicates this logic and makes this unnecessarily complex.
