### ISSUE TITLE
Unable to make payment using test credit card 

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#154]
**Describe the bug**
Unable to complete payment using test credit card. This bug is reported in the JS console. This unexpected behavior applies found on both successful and declined credit cards. 

```
Uncaught (in promise) ReferenceError: paymentId is not defined
```

**To Reproduce**
1. Login: `tickets+common-user@fnf.org`/`AXLE-gastric-mekong`
2. Go to: https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3031/payments/new
3. Enter these credit card details obtained from [Stripe Credit Card page](https://docs.stripe.com/testing#cards)
```
Will be declined: 4000 0000 0000 0002
Will be successful: 4242424242424242
Expiration: 12/34
CRC: 123
Country: USA
Zip: 94103
```
4. Click on "Pay Now"

**Expected behavior**
Payment should be successful on test credit cards that are designed to always pass

**Screenshots**
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/0a06b2d8-6616-4c27-b36e-1efac741c5bf)  

**Version info**  
SHA: fd9e2acc9b165c2e18d4997647a249b992cebedc
App Version: `1.0.1`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`

**Comment by kigster** [comment]
@beingmattlevy I believe you removed `paymentId` from the JSON returned by create action?

**Comment by beingmattlevy** [comment]
Fixed. Will deploy once tests pass

**Comment by yarunluon** [comment]
Confirmed I can make a successful payment using a Stripe test credit card
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/97dbe57f-add3-4c21-8e30-39979db953d9)

**Comment by yarunluon** [comment]
Confirmed the declined payment payment flow works
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/9c6f3633-013b-44e5-9a37-9371897cbdad)

**Comment by yarunluon** [comment]
used a credit card with a low risk factor and it was accepted by Stripe
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/7c68d63b-088f-4fe8-98df-a93cf9da6f1f)

```
Low risk factor. Missing address line
4000000000000044
```
