### ISSUE TITLE
Alternative payment method generates server error

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#157]
**Describe the bug**
Submitting a request to pay by an alternative payment method besides credit card generates a server error

**To Reproduce**
1. Go to alternative payment method page.
    1. Url: [https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3035/payments/new/other](https://tickets.fnf.events/events/14-fnf-2024-summer-campout/ticket_requests/3035/payments/new/other)
    2. User: `tickets+payment-received@fnf.org`
    3. Pass: `bribe-ASHEN-bewitch`
4. Fill out the text area. Gibberish is fine.
5. Click on "Submit request".
6. See error

**Expected behavior**
A message sent to tickets@fnf.org that an alternative payment will be used.

**Screenshots**
![alternative-payment-fail](https://github.com/fnf-org/TicketBooth/assets/1328337/8d3ac447-9e1f-4d94-a941-b4a658955399)

**Logs**
New Relic Logs
[https://onenr.io/0OQMddM8NjG](https://onenr.io/0OQMddM8NjG)
```
NoMethodError (undefined method `back_url' for #<PaymentsController:0x0000000003b290>):  app/controllers/payments_controller.rb:97:in `sent'
```

**Version info**  
App Version: `1.0.1`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`

**Comment by beingmattlevy** [comment]
This has been fixed

**Comment by yarunluon** [comment]
Confirmed that users can select an Alternative Payment method
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/2866da4e-b212-4c5c-a747-51fcc25a2a53)
