### ISSUE TITLE
Cannot submit ticket request because of mismatched client/server-side validation

### ISSUE THREAD

**Issue by yarunluon** [fnf-org/TicketBooth#179]
**Describe the bug**  
Users are unable to submit Ticket Requests because max char of client-side does not match server-side. Client-side is 250. Server side is 200. If a user types between 200 to 250 characters, the form is requested with new error message, because the server returns a 200 instead of a 400.

**To Reproduce**  
1. Go to the Ticket Request page
2. Select Planner, Lead Coordinator, Skipper, Other as a role. The Role textarea does not appear for Volunner, but will for the other roles. 
3. Fill the textarea with content that exceeds 200 characters
4. Submit the form
5. Nothing happens

**Expected behavior**  
Users should be able to submit the form. 

**Possible solutions**
1. Make the char limitation the same between client-side and server-side
2. Server should return a 400 and not a 200 for rejected responses

**Screenshots**  
![image](https://github.com/fnf-org/TicketBooth/assets/1328337/d16107f7-8e08-4294-96ee-d5615718dbe7)

**Version info**  
Sha: 73823b95414d7ee69dd9c0f270598b960e05fa7a 
App Version: `1.0.2`  
Rails: `7.1.3.2`  
Ruby: `3.2.3`  
Mode: `production`

**Comment by kigster** [comment]
This has been long fixed.
