### ISSUE TITLE
Hazards in the data model.

### ISSUE THREAD

**Issue by mike-matera** [fnf-org/TicketBooth#30]
Description in note below!

**Comment by mike-matera** [comment]
There are two man issues with the data model: 

1. The database is not normalized. For example, the number of early arrival passes is encoded in **both** the `eald_payments` table and in the `ticket_requests` table. So what if they don't match? Which one is right? A bug in the application could make it impossible to recover information about items where money was transacted. 
2. There are places that require transactions. If [this line](https://github.com/fnf-org/TicketBooth/blob/main/app/controllers/payments_controller.rb#L84) fails for any reason, it's possible to leave the database in an inconsistent state. Where `mark_received` has happened but `mark_complete` has not. **This has happened.** When the app was released in 2022 there were not enough resources allocated to the container and crashed under load. Many users were left in a broken state and I had to personally issue SQL commands to muck it all out. 

This site handles money. Having these kinds of bugs are inexcusable and asking for trouble. The longer it continues to serve FnF community the more likely it is to double charge someone or forget a recipt.

**Comment by kigster** [comment]
There are good points here, however it would be great if we could break this ticket up into several smaller concrete issues that need addressing.

As it stands right now it's too general and "redesign data model" is a very controversial title, perhaps intentionally.

I'd prefer that each ticket zeroed in on a specific issue like why is something demoralized or the need for transactions in various places.

As it stands currently it's an expression of concern, however valid, is hardly actionable.

**Comment by kigster** [comment]
I split the two specific issues into two separate tickets. If there are other issues like this please feel free to create a new ticket. Closing this one.
