### ISSUE TITLE
Ensure transactionality around important financial operations 

### ISSUE THREAD

**Issue by kigster** [fnf-org/TicketBooth#60]
Reported by @mike-matera 

There are various places in the app that require transactions. 

If [this line](https://github.com/fnf-org/TicketBooth/blob/main/app/controllers/payments_controller.rb#L84) fails for any reason, it's possible to leave the database in an inconsistent state. 

Where `mark_received` has happened but `mark_complete` has not. 

This has happened. When the app was released in 2022 there were not enough resources allocated to the container and it crashed under load. Users were left in a broken state and I had to personally issue SQL commands to muck it all out.

> question: why were there insufficient resources allocated to the app?

### Rhetorical Rant

This site handles money. Having these kinds of bugs are inexcusable and asking for trouble. The longer it continues to serve FnF community the more likely it is to double charge someone or forget to Issue a receipt.

## Conclusion

it's worth investigating further.

**Comment by mike-matera** [comment]
The answer to your question is that you didn't tell me that you were going to release the ticket site to planners so, when you did, the infrastructure was not ready. :-P

**Comment by kigster** [comment]
We added transactions. Closing
