### ISSUE TITLE
Migrate away from passwords to at least SSO, if not MFA

### ISSUE THREAD

**Issue by ev1lm0nk3y** [fnf-org/TicketBooth#82]
_This should be a requirement in a near future version_

Proposal: Use other entities to provide us with Authentication and Authorization through SAML or OAuth

Passwords are high-risk no reward level bad, plain and simple. SSO sign in could be easily migrated from storing passwords to just keeping their username in our database. Most people have google, fb, github, etc accounts already so those are easy for us to resolve.

If needed, FnF could have a small authenticator application that can register people.

**Comment by kigster** [comment]
While is entirely possible with Devise, this is not a priority today. 

We do not store credit card information, the data is is behind SSL, and we lock your account until 10 unsuccessful attempts.

**Comment by kigster** [comment]
Closing for mow
